# Generated by Django 4.2.6 on 2023-11-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_description_alter_product_past_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='topic',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
