# Generated by Django 4.2.6 on 2023-12-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_alter_orderitem_product_productreview_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='state',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
    ]
