# Generated by Django 4.2.6 on 2024-01-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_related_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Waiting for confirmation"),
                    (2, "Order confirmed"),
                    (3, "Shipped"),
                    (4, "Out for delivery"),
                    (5, "Delivered"),
                    (6, "Unsuccessful delivery"),
                    (7, "Order canceled"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="ordertracking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Waiting for confirmation"),
                    (2, "Order confirmed"),
                    (3, "Shipped"),
                    (4, "Out for delivery"),
                    (5, "Delivered"),
                    (6, "Unsuccessful delivery"),
                    (7, "Order canceled"),
                ]
            ),
        ),
    ]
