# Generated by Django 4.2.6 on 2023-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
